defaults:
  - main_darkstore_continuous_config_base
  - _self_

name: 'ds_continuous'
size_x: 24
size_y: 15
num_scenes: 1
num_workers: 1
layout_gen_type: PROCEDURAL_TENSOR_FIELD
randomize_layout: true
randomize_arrangements: true

inactive_wall_shelvings_occupancy_width: 0.4
inactive_shelvings_occupancy_width: 1.0
fixtures_occupancy_width: 0.2
passage_width: 2.0
inactive_shelvings_skip_prob: 0.1


random_seed: 42

active_shelvings_list:
  - name: 'mixed_shelf'
    filling_type: BOARDWISE_COLUMNS
    x_gap: 0.01
    y_gap: 0.01
    shelf_asset: fixtures.shelf_metal
    shuffle_boards: True
    board_product_numcol:
      2:
        food.dairy_products.milkCarton: 2
      4:
        food.drinks.coffeePackaging: 1
      
inactive_shelvings_list:
  - fixtures.shelf
  - fixtures.shelf_metal
  - fixtures.small_shelf_two_sided

inactive_wall_shelvings_list:
  - fixtures.freezer_large

scene_fixtures_list: 
  - fixtures.pile_of_pallets
  - fixtures.pallets_and_boxes
  - fixtures.freezer_nestle


fake_arrangements_mapping:
  fixtures.shelf:
    - fixtures.shelf_fake_1
    - fixtures.shelf_fake_2
    - fixtures.shelf_fake_3
  fixtures.shelf_metal:
    - fixtures.shelf_metal_fake_1
    - fixtures.shelf_metal_fake_2
  fixtures.small_shelf_two_sided:
    - fixtures.small_shelf_two_sided_fake_1
    - fixtures.small_shelf_two_sided_fake_1
  